---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # 여러분의 backend image 주소를 입력해주세요.
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_67234d158ca8
          env:
            - name: TZ
              value: Asia/Seoul
            - name: DATABASE_URL
              value: jdbc:mariadb://mariadb:3306/krampoline
            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: bucketname
            - name: AWS_ACCESSKEY # application.yml의 키
              valueFrom:
                secretKeyRef:
                  name: aws-secret # secret.yml 이름
                  key: accesskey # secret.yml에서의 키
            - name: AWS_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: secretkey
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/dog_walking?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: PASSWORD
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: JWT_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret-key-secret
                  key: secretKey
          resources:
            requests:
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /api/test
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
